### ISSUE TITLE
Latest organization-related news

### ISSUE THREAD

**Issue by Minoru** [codingteam/Gestalt#1]
This is feature one of the three that @ForNeVeR [originally envisioned](http://0xd34df00d.me/logs/chat/codingteam@conference.jabber.ru/2015/04/14.html#01:52:19).

Gestalt should look through all the repositories that belong to the organization and report, in reverse chronological order:
- updates to issues;
- bugs fixed;
- pull requests submitted.

(The list might be incomplete, suggestions are welcome).

**Comment by ForNeVeR** [comment]
I like how you've organized my proposals, that's really nice. Thank you!

**Comment by ForNeVeR** [comment]
Regarding the topic: we maybe also want to announce all recent pushes.

**Comment by Minoru** [comment]
Should we also announce comments on pull requests? I'm in two minds about this.

**Comment by ForNeVeR** [comment]
Let's announce them at start. We can always disable them later if they become annoying.

**Comment by ForNeVeR** [comment]
What will contain a `count` field of `"subject": "push"` object?

**Comment by ForNeVeR** [comment]
There should be a possibility to get news from time period. Something like

```
/organizations/codingteam/news?from=2015-01-01T00:00:00Z&to=2015-01-02T00:00:00Z
```

_(And I don't know if these `:` should be URL-encoded, check later.)_

Or maybe we will want to introduce some syntetic `timestamp` to every news item so they can be queried sequentially without messing with dates and times (it can be useful with any history-altering events).

**Comment by ForNeVeR** [comment]
I've changed the `issue` field to `issues` array because there can be multiple labels.

**Comment by Minoru** [comment]
> What will contain a count field of "subject": "push" object?

It's the number of commits that the user pushed. GitHub gives us a lot more detail, like hashes and branch and so on, but I don't think we'll need it for short summary on the site.

> Or maybe we will want to introduce some syntetic `timestamp` to every news item so they can be queried sequentially without messing with dates and times (it can be useful with any history-altering events).

Events are unalterable, I believe, so we should be safe with ordinary timestamps. I've added `since` and `until` GET parameters to the draft. Thank you for the feedback!

**Comment by ForNeVeR** [comment]
> It's the number of commits that the user pushed.

Maybe then call it "commits"? Because the "count" name is slightly misleading - it's not obvious what exactly it will count.

> I've added `since` and `until` GET parameters to the draft. 

Okay, that should be enough.

**Comment by Minoru** [comment]
> Maybe then call it "commits"? Because the "count" name is slightly misleading - it's not obvious what exactly it will count.

Good point. Changed the name to `commits_count` (don't want to use `commits` because we might want to use it later on if we decide to provide some commits-specific info).

**Comment by Minoru** [comment]
Closing the issue due to the stabilization of version 1 of the API.
