### ISSUE TITLE
User analytics

### ISSUE THREAD

**Issue by Minoru** [codingteam/Gestalt#3]
This is feature three of the three that @ForNeVeR [originally envisioned](http://0xd34df00d.me/logs/chat/codingteam@conference.jabber.ru/2015/04/14.html#01:52:19).

Gestalt should make it easy to answer questions like "who's codingteam's top Scala coder?" and "who's codingteam's top five programming language polyglots?" In order to do so, the service should crawl over all the _public_ members of the organization and collect their language preferences.

**Comment by ForNeVeR** [comment]
We can later invent some advanced metrics, but as start let's get something accessible, like count of repositories per language for each user.

**Comment by ForNeVeR** [comment]
I would like to rename the `analytics` URL to `users` because it currently only provides such a basic data.

**Comment by ForNeVeR** [comment]
Also there seems to be inconsistency with `"user-url"` and `"repos-per-language"` keys - I think we should replace dashes with underscores.

**Comment by Minoru** [comment]
> I would like to rename the `analytics` URL to `users` because it currently only provides such a basic data.

I'd like to object: we'll probably add new metrics soon enough, so what's the point in renaming if we're going to switch back a few weeks from now?

`user-url` and `repos-per-language` are typos again; thanks for spotting! Fixed.

**Comment by ForNeVeR** [comment]
Well, okay, let it be `analytics` for now.

**Comment by Minoru** [comment]
Closing the issue due to the stabilization of version 1 of the API.
