### ISSUE TITLE
Devise an API

### ISSUE THREAD

**Issue by Minoru** [codingteam/Gestalt#4]
It's better to establish our interface right away, so others can go ahead with implementing clients while we work on the service. it will also help us understand precisely what we're going to build.

This issue should be used to discuss specifics of the API. To discuss the features of the service, please use separate issues.

**Comment by Minoru** [comment]
@ForNeVeR already said in the chatroom that he wants the service to have HTTP interface — I have no objections.

This, I believe, also implies that the API is going to be RESTful. I have no experience with that and am going to read up a bit before suggesting anything specific.

It will probably make sense to use JSON as data representation format, at least for now. We can also go a bit crazy and try to use Yaml, taking this as yet another opportunity to contribute to the ecosystem — apparently [there's no mature Yaml library for Erlang](https://stackoverflow.com/questions/2392907/there-is-no-mature-yaml-library-for-erlang).

**Comment by ForNeVeR** [comment]
I don't think YAML could be useful here. I'd suggest us to stick with JSON.

**Comment by ForNeVeR** [comment]
Well, I think that the current API is a good enough for implementation. Let's use it as a basic variant and discuss all further improvements on a case basis.

**Comment by Minoru** [comment]
With [public API draft](https://github.com/codingteam/Gestalt/wiki/Public-API) not being changed for a week, I deem this issue resolved.
