### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/Gestalt#5]
Users complain they cannot find a Readme. We should add it. And a license also.

**Comment by Minoru** [comment]
I'll add the README right away, then.

Are you okay with using [3-clause BSD license](http://opensource.org/licenses/BSD-3-Clause)?

**Comment by ForNeVeR** [comment]
I'd prefer MIT but you're free to choose it yourself; I'm okay with both of these licenses.
