### ISSUE TITLE
Project infrastructure

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/Gestalt#6]
We should add all the ordinary shit: Travis CI integration, auto deployment, etc.

**Comment by Minoru** [comment]
Can you take care of the Travis, please? I'd rather focus on documentation and laying the groundwork for the moment.

Auto deployment? I have no idea how _that_ is supposed to work. We'll have rebar releases at some point, yes, but we don't even know where to host this thing (well, at least I don't).

**Comment by ForNeVeR** [comment]
Yes, I created this issue with myself as its implementor in mind :)

We can easily find some platform to host it when something will be ready; we have a plenty of options and I will take care of it.

And yeah, I'll enable Travis soon.

**Comment by ForNeVeR** [comment]
I think that everything is okay now. We'll solve the autodeployment problem when the stars are right.

**Comment by rexim** [comment]
> We'll solve the autodeployment problem when the stars are right.

Created an issue for autodeployment #11

@Minoru, Mr. ForNeVeR likes to close unfinished issues. Please, do not let him do that.

**Comment by ForNeVeR** [comment]
Oh you ._.
